Repository BuildForSDG/Team-269-Frontend, pull requests merged in 2020-05, with the labels that each got.

#2 Added ReactJS Scaffolding to Master Branch
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/app.js
  src/index.css
  src/index.html
  src/index.js
  src/logo.svg
  src/serviceWorker.js
  src/setupTests.js
Labels: Ready For Review, enhancement

#16 chore: delete default d-rating badge
  README.md
Labels: Ready For Review

#21 style: added spaces in sections
  README.md
Labels: documentation

#24 Ft landing page
  src/App.css
  src/App.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/index.js
  src/components/PageFooter/PageFooter.css
  src/components/PageFooter/index.js
  src/components/PageHeader/PageHeader.css
  src/components/PageHeader/index.js
  src/components/PrimaryButton/PrimaryButton.css
  src/components/PrimaryButton/index.js
  src/images/statcon.png
  src/images/statsicon.png
  src/index.js
  src/router.js
Labels: Ready For Review

#23 docs: update meta data
  app.properties
Labels: documentation

#27 chore: add link to live app
  README.md
Labels: Ready For Review

#28 Fx sign up page
  jest.config.js
  src/App.css
  src/components/LandingPage/LandingPage.css
  src/components/PageHeader/PageHeader.css
  src/components/PrimaryButton/PrimaryButton.css
  src/components/signup/SignUp.css
  src/components/signup/SignUp.js
  src/index.css
Labels: Ready For Review, enhancement

#29 Ft login page
  src/components/LoginPage/LoginPage.css
  src/components/LoginPage/index.js
  src/router.js
Labels: Ready For Review

#32 Ft forgotpassword page
  src/components/ForgotPassword/ForgotPassword.css
  src/components/ForgotPassword/index.js
  src/router.js
Labels: Ready For Review

#37 Ft implement sign up functionality
  package-lock.json
  package.json
  src/App.js
  src/components/LoginPage/LoginPage.css
  src/components/LoginPage/index.js
  src/components/signup/SignUp.css
  src/components/signup/SignUp.js
  yarn.lock
Labels: Ready For Review
